export const weatherMap = [
  { id: 0, desc: "Чистое небо", iconName: "WiDaySunny" },
  { id: 1, desc: "В основном ясно", iconName: "WiDaySunnyOvercast" },
  { id: 2, desc: "Переменная облачность", iconName: "WiCloud" },
  { id: 3, desc: "пастмурно", iconName: "WiCloudy" },
  { id: 45, desc: "туман", iconName: "WiFog" },
  { id: 48, desc: "Густой туман", iconName: "WiHail" },
  { id: 51, desc: "Лёгкая морось", iconName: "WiDayRainMix" },
  { id: 53, desc: "Умеренная морось", iconName: "WiRaindrops" },
  { id: 55, desc: "Интенсивная морось", iconName: "WiRaindrops" },
  { id: 56, desc: "Лёгкий Морозный дождь", iconName: "WiDaySleet" },
  { id: 57, desc: "Плотный Морозный дождь", iconName: "WiDaySleet" },
  { id: 61, desc: "Небольшой дождь", iconName: "WiDayRain" },
  { id: 63, desc: "Умеренный дождь", iconName: "WiDayRainWind" },
  { id: 65, desc: "Интенсивный дождь", iconName: "WiDayShowers" },
  { id: 66, desc: "Небольшой Ледяной дождь", iconName: "WiDaySleet" },
  { id: 67, desc: "Интенсивный ледяной дождь", iconName: "WiDaySleet" },
  { id: 71, desc: "Слабый снегопад", iconName: "WiDaySnow" },
  { id: 73, desc: "Умеренный снегопад", iconName: "WiDaySnowWind" },
  { id: 75, desc: "Сильный снегопад", iconName: "WiSnow" },
  { id: 77, desc: "Снежная крупа", iconName: "WiSnow" },
  { id: 80, desc: "Ливень слабый", iconName: "WiDayShowers" },
  { id: 81, desc: "Ливень умеренный", iconName: "WiShowers" },
  { id: 82, desc: "Сильный ливень", iconName: "WiShowers" },
  { id: 85, desc: "Снегопад слабый", iconName: "WiSnow" },
  { id: 86, desc: "Снегопад сильный", iconName: "WiSnowWind" },
  { id: 95, desc: "Гроза", iconName: "WiDaySnowThunderstorm" },
  { id: 96, desc: "Гроза с градом", iconName: "WiThunderstorm" },
  { id: 99, desc: "Гроза с градом", iconName: "WiThunderstorm" },
];